name: Deploy to AWS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  

permissions:
  id-token: write   # Required for requesting the OIDC JWT
  contents: read    # Required to check out code

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::697245141874:role/GitHubActions-Deployment-Role
          aws-region: us-east-1

      - name: Test AWS Connectivity
        run: |
          aws sts get-caller-identity